apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}
          containers:
          - name: {{ .Release.Name }}
            image: {{ .Values.image.repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}
            args:
            - /scripts/restart_all_in_namespace.sh
            - {{ .Release.Namespace }}
          restartPolicy: Never